---
name: luna_pinyin_simp.config ##注意name和文件名一致
version: "2020.6.7"
sort: by_weight
use_preset_vocabulary: true
# 此处为 输入法所用到的词库，既补充拓展词库的地方
import_tables:
    - luna_pinyin.sougou
    - luna_pinyin
...